name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache
      uses: Swatinem/rust-cache@v2

    - name: Check format
      run: cargo fmt --check

    - name: Check
      run: cargo check

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test

    - name: Build
      run: cargo build --release --locked