name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies and build
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --all --verbose

      - name: Build release
        run: cargo build --release --verbose
