name: CI

on:
  # Run on any PR
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check that code can compile
      run: cargo check 

    - name: Check that tests pass
      run: cargo test

    - name: Check that build works
      run: cargo build --release
